function(create_algostruct_unit_test)
    cmake_parse_arguments(CREATE_TEST "" "NAME" "SRC_TEST;SRC_CORE" ${ARGV})
    if (CREATE_TEST_SRC_CORE)
        foreach(SRC ${CREATE_TEST_SRC_CORE})
            string(REPLACE "${PROJECT_SOURCE_DIR}/tests/unit/" "${PROJECT_SOURCE_DIR}/src/" RES_SRC "${CMAKE_CURRENT_SOURCE_DIR}/${SRC}")
            list(APPEND SRC_CORE_LIST "${RES_SRC}")
        endforeach()
    endif()
    add_executable(${CREATE_TEST_NAME} ${CREATE_TEST_SRC_TEST} ${CREATE_TEST_SRC_CORE_LIST})
    target_link_libraries(${CREATE_TEST_NAME} ${GTEST_BOTH_LIBRARIES} Threads::Threads)
    target_include_directories(${CREATE_TEST_NAME} PUBLIC
            ${GTEST_INCLUDE_DIRS} ${MAIN_HEADERS} ${SUPPORT_HEADERS})
    add_test(NAME ${CREATE_TEST_NAME} COMMAND ${CREATE_TEST_NAME})
endfunction()
